/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace SmartVideo.Transport
{
  public enum MEDIATYPE
  {
    JPG = 1,
    PNG = 2,
    MP4 = 3,
  }
}
